
import type { Timestamp } from 'firebase/firestore';

// Input data for generating an itinerary
export interface ItineraryInput {
  destination: string;
  travelDates: string; // Consider using Date objects or a date range picker later
  groupSize: number;
  activityPreferences: string;
  groupType: string; // e.g., 'family', 'friends', 'colleagues', 'solo'
  tripLength: number; // in days
}

// The structure of the generated itinerary content
export interface GeneratedItinerary {
  // This will hold the detailed string output from the AI
  itinerary: string;
  // Optionally add structured data later if the AI provides it
  // dailyPlan?: { day: number; description: string; activities: string[] }[];
}

// The full itinerary object stored in Firestore
export interface Itinerary extends ItineraryInput, GeneratedItinerary {
  id?: string; // Firestore document ID
  userId: string; // ID of the user who created it
  title: string; // User-defined title for the itinerary (e.g., "Paris Trip Summer 2024")
  createdAt: Timestamp;
  updatedAt: Timestamp;
  summary?: string; // Optional summary generated by AI
}
